version: '3.8'

services:
  db:
    image: "postgres"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=crm_db_user
      - POSTGRES_DB=crm_db
    expose:
      - 5432
    ports:
      - 5432:5432
  
  api:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    links:
      - db
    expose:
      - 8000
    command: ./crm/manage.py runserver 0.0.0.0:${PORT:-8000}
    stdin_open: true
    tty: true