# Generated by Django 4.1.3 on 2022-11-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='name_verified',
            field=models.BooleanField(default=False),
        ),
    ]
